# Generated by Django 4.2 on 2023-05-04 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='indigrients',
            new_name='indgredients',
        ),
    ]
