# Generated by Django 3.2 on 2023-05-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_indigrients_recipe_indgredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritereceipe',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Рецепты в избранном'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientinrecipesamount',
            options={'verbose_name': 'Количество ингредиентов', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.RenameField(
            model_name='favoritereceipe',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Единица измерения количества ингредиента', max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Название ингредиента', max_length=200, verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipesamount',
            name='amount',
            field=models.IntegerField(help_text='Необходимое количество данного ингредиента', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='indgredients',
            field=models.ManyToManyField(help_text='Ингредиенты для приготовления по рецепту', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddConstraint(
            model_name='favoritereceipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='favorite_recipe'),
        ),
        migrations.AddConstraint(
            model_name='ingredientinrecipesamount',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='amount_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipe_in_shopping_cart'),
        ),
    ]
