# Generated by Django 3.2 on 2023-05-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ингредиенты для приготовления по рецепту', through='recipes.IngredientInRecipesAmount', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
